parser: babel-eslint

plugins:
- prettier

extends:
- eslint:recommended
- plugin:prettier/recommended

env:
  node: true
  es6: true

parserOptions:
  sourceType: module

overrides:
  - files: '**/__tests__/*.test.js'
    env:
      jest: true
