language: node_js
node_js:
- 10
- 12
script:
- yarn test
- yarn lint
deploy:
  provider: npm
  email: JesseTheGibson@gmail.com
  skip_cleanup: true
  api_key:
    secure: elSTDzrAEvVEe49AmBSAnMsOw1q9Vm071gVzJLva1JhQt7CRI/n/E8/lhbxeSAIIOzXqPWO30E2OemwYs1TAGv3Si9P94BJKozAWfmNmN56j8Mk8ZVI0dO61DwEbsBw1Iv7QwPPVz7Un59Dd/oMri3yeeuOraYTIjyMFwPKbsCwFpADGBlIuNVsDFob3r6SAwgeBEZ/HPELH/ef6iTgIHABtuZrxCMZaskQbdQpHSNiXNAs7AlThdjjy3JaHi/sOMAm8WDmP5ahp8GprjjlMyZQU3bFtwvndgjhyrKjHNjNs1cV9vFmWDHIuavITVtZOdK6Rqywi9FDq8ESxk8lljNAid5DBdhyOBke+YTFcaYxKJ6ppqvCRIW7L96oTE07Q7EOhioRFEBkiRLaq9oV81kxVGg89uOpVMj0PUWMW6XjmyA/KUUus2kfggIWV1LneCx0sRQ0rRBVhNzUzv2ev5bGM0tRRwEteZshcD/Xl/YRWcPBKcWlrFc+4iU81ZSOU6XvpdpsaJrVj7g3HByQPvkLkh9YIRyEcujdnbekZcsMiPVTdfomgQdc7X9fIyDpLjgqz8c9iJ6zbxvn3riT6A/wAPFPOtHz73fKwTH1BP/TRpgRQ0xe8COYatCDvj44B5AWf06yAYhqalDfLj8WvTda4GkJ4TxQ9smurXHLTH3s=
  on:
    tags: true
    repo: PsychoLlama/hue-connect
