language: node_js
node_js:
- 8
- 10
script:
- yarn test
- yarn lint
deploy:
  provider: npm
  email: Jesse_Gibson@me.com
  skip_cleanup: true
  api_key:
    secure: IApFhL8YEAM8fJtRteEOU323RWK0vqJNsbz7nDtW+OwFcJxrpfZvveRvbs2tU+xUoRfDbtb9RaqFLuxPi+rk0VE0GYCWaEZe37MsKQuBPYbY1rfQ+1Ll2DuYvjBP3V8hGXDB1Nzv2vnaRzp4RrSIPF+D4J4tRNDiPIzA5/PMz58aYmaL4aM2EXU+t13M4rgoWnHlYWXrma+lmr07rOudL/bXV0jFJgdV00wgofHsFUWBP3OdJnQ+Vg5SqSy3znyL+RmMRvNHfjuUKGNRz0vXdu9SNXGHOMJ+44nzARt39MFlcwickm3Hh9EeJ4TEHjPzaYpQ5u1EYoZiGUmzizWFhDdnRU6k3FJaEQxMqbqfP3sgfAqrQF0LO59eHtRNBbEIsnItXKXfUSNM6zQdrJ3HClJVd/PWAgjgcWrV6xwEAWTRWapAQqUoghRV59cus701m3fHi60NIZIPZ1vju6EvZo68gtSuiQSx+Mk6VTDheBlYCG7YlCY4NUHhcsjFbsR1cpJDHUq297pkeROoqfNAV9Tj3aq1QXGscdCS6TqxPyJf3GGzD3pI9mgwrwXSrdlEXqyx9ho8o1/kLnPO50mqCvbBesTBngrYG1FvMRT4dvSeThBoAqot8XwhnTTi1sHOCEpchDcXgal1QuC+HXkCGSY9FRJC3DZtTvHH7I7iYeo=
  on:
    tags: true
    repo: PsychoLlama/hue-connect
