name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 16]
    name: Node ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: Install node v${{ matrix.node_version }}
        with:
          node-version: ${{ matrix.node_version }}
      - uses: bahmutov/npm-install@v1
      - name: Run tests
        run: yarn -s test
